package com.lzdn.aswxmall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class AswxmallRebatesCreateOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public AswxmallRebatesCreateOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public AswxmallRebatesCreateOrderExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public AswxmallRebatesCreateOrderExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        AswxmallRebatesCreateOrderExample example = new AswxmallRebatesCreateOrderExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public AswxmallRebatesCreateOrderExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public AswxmallRebatesCreateOrderExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andIdEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andIdNotEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andUserIdEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("user_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andUserIdNotEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("user_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andUserIdGreaterThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("user_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andUserIdGreaterThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("user_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andUserIdLessThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("user_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andUserIdLessThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("user_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderIdEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderIdNotEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderIdGreaterThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderIdGreaterThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderIdLessThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderIdLessThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdIsNull() {
            addCriterion("order_user_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdIsNotNull() {
            addCriterion("order_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdEqualTo(Integer value) {
            addCriterion("order_user_id =", value, "orderUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderUserIdEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_user_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderUserIdNotEqualTo(Integer value) {
            addCriterion("order_user_id <>", value, "orderUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderUserIdNotEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_user_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderUserIdGreaterThan(Integer value) {
            addCriterion("order_user_id >", value, "orderUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderUserIdGreaterThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_user_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_user_id >=", value, "orderUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderUserIdGreaterThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_user_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderUserIdLessThan(Integer value) {
            addCriterion("order_user_id <", value, "orderUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderUserIdLessThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_user_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_user_id <=", value, "orderUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderUserIdLessThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_user_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderUserIdIn(List<Integer> values) {
            addCriterion("order_user_id in", values, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdNotIn(List<Integer> values) {
            addCriterion("order_user_id not in", values, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdBetween(Integer value1, Integer value2) {
            addCriterion("order_user_id between", value1, value2, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_user_id not between", value1, value2, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderActualPriceIsNull() {
            addCriterion("order_actual_price is null");
            return (Criteria) this;
        }

        public Criteria andOrderActualPriceIsNotNull() {
            addCriterion("order_actual_price is not null");
            return (Criteria) this;
        }

        public Criteria andOrderActualPriceEqualTo(BigDecimal value) {
            addCriterion("order_actual_price =", value, "orderActualPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderActualPriceEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_actual_price = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderActualPriceNotEqualTo(BigDecimal value) {
            addCriterion("order_actual_price <>", value, "orderActualPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderActualPriceNotEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_actual_price <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderActualPriceGreaterThan(BigDecimal value) {
            addCriterion("order_actual_price >", value, "orderActualPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderActualPriceGreaterThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_actual_price > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderActualPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("order_actual_price >=", value, "orderActualPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderActualPriceGreaterThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_actual_price >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderActualPriceLessThan(BigDecimal value) {
            addCriterion("order_actual_price <", value, "orderActualPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderActualPriceLessThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_actual_price < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderActualPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("order_actual_price <=", value, "orderActualPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andOrderActualPriceLessThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("order_actual_price <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOrderActualPriceIn(List<BigDecimal> values) {
            addCriterion("order_actual_price in", values, "orderActualPrice");
            return (Criteria) this;
        }

        public Criteria andOrderActualPriceNotIn(List<BigDecimal> values) {
            addCriterion("order_actual_price not in", values, "orderActualPrice");
            return (Criteria) this;
        }

        public Criteria andOrderActualPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_actual_price between", value1, value2, "orderActualPrice");
            return (Criteria) this;
        }

        public Criteria andOrderActualPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_actual_price not between", value1, value2, "orderActualPrice");
            return (Criteria) this;
        }

        public Criteria andBeforeAmountsIsNull() {
            addCriterion("before_amounts is null");
            return (Criteria) this;
        }

        public Criteria andBeforeAmountsIsNotNull() {
            addCriterion("before_amounts is not null");
            return (Criteria) this;
        }

        public Criteria andBeforeAmountsEqualTo(BigDecimal value) {
            addCriterion("before_amounts =", value, "beforeAmounts");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andBeforeAmountsEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("before_amounts = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBeforeAmountsNotEqualTo(BigDecimal value) {
            addCriterion("before_amounts <>", value, "beforeAmounts");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andBeforeAmountsNotEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("before_amounts <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBeforeAmountsGreaterThan(BigDecimal value) {
            addCriterion("before_amounts >", value, "beforeAmounts");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andBeforeAmountsGreaterThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("before_amounts > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBeforeAmountsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("before_amounts >=", value, "beforeAmounts");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andBeforeAmountsGreaterThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("before_amounts >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBeforeAmountsLessThan(BigDecimal value) {
            addCriterion("before_amounts <", value, "beforeAmounts");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andBeforeAmountsLessThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("before_amounts < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBeforeAmountsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("before_amounts <=", value, "beforeAmounts");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andBeforeAmountsLessThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("before_amounts <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBeforeAmountsIn(List<BigDecimal> values) {
            addCriterion("before_amounts in", values, "beforeAmounts");
            return (Criteria) this;
        }

        public Criteria andBeforeAmountsNotIn(List<BigDecimal> values) {
            addCriterion("before_amounts not in", values, "beforeAmounts");
            return (Criteria) this;
        }

        public Criteria andBeforeAmountsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("before_amounts between", value1, value2, "beforeAmounts");
            return (Criteria) this;
        }

        public Criteria andBeforeAmountsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("before_amounts not between", value1, value2, "beforeAmounts");
            return (Criteria) this;
        }

        public Criteria andRebatesIsNull() {
            addCriterion("rebates is null");
            return (Criteria) this;
        }

        public Criteria andRebatesIsNotNull() {
            addCriterion("rebates is not null");
            return (Criteria) this;
        }

        public Criteria andRebatesEqualTo(BigDecimal value) {
            addCriterion("rebates =", value, "rebates");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andRebatesEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("rebates = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRebatesNotEqualTo(BigDecimal value) {
            addCriterion("rebates <>", value, "rebates");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andRebatesNotEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("rebates <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRebatesGreaterThan(BigDecimal value) {
            addCriterion("rebates >", value, "rebates");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andRebatesGreaterThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("rebates > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRebatesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rebates >=", value, "rebates");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andRebatesGreaterThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("rebates >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRebatesLessThan(BigDecimal value) {
            addCriterion("rebates <", value, "rebates");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andRebatesLessThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("rebates < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRebatesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rebates <=", value, "rebates");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andRebatesLessThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("rebates <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRebatesIn(List<BigDecimal> values) {
            addCriterion("rebates in", values, "rebates");
            return (Criteria) this;
        }

        public Criteria andRebatesNotIn(List<BigDecimal> values) {
            addCriterion("rebates not in", values, "rebates");
            return (Criteria) this;
        }

        public Criteria andRebatesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rebates between", value1, value2, "rebates");
            return (Criteria) this;
        }

        public Criteria andRebatesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rebates not between", value1, value2, "rebates");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNull() {
            addCriterion("balance is null");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNotNull() {
            addCriterion("balance is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceEqualTo(BigDecimal value) {
            addCriterion("balance =", value, "balance");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andBalanceEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("balance = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBalanceNotEqualTo(BigDecimal value) {
            addCriterion("balance <>", value, "balance");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andBalanceNotEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("balance <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThan(BigDecimal value) {
            addCriterion("balance >", value, "balance");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andBalanceGreaterThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("balance > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("balance >=", value, "balance");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andBalanceGreaterThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("balance >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBalanceLessThan(BigDecimal value) {
            addCriterion("balance <", value, "balance");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andBalanceLessThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("balance < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("balance <=", value, "balance");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andBalanceLessThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("balance <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBalanceIn(List<BigDecimal> values) {
            addCriterion("balance in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotIn(List<BigDecimal> values) {
            addCriterion("balance not in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balance between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balance not between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("`type` =", value, "type");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andTypeEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("`type` = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("`type` <>", value, "type");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andTypeNotEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("`type` <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("`type` >", value, "type");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andTypeGreaterThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("`type` > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("`type` >=", value, "type");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andTypeGreaterThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("`type` >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("`type` <", value, "type");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andTypeLessThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("`type` < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("`type` <=", value, "type");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andTypeLessThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("`type` <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("create_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeNotEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("create_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("create_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("create_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("create_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanOrEqualToColumn(AswxmallRebatesCreateOrder.Column column) {
            addCriterion(new StringBuilder("create_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        private AswxmallRebatesCreateOrderExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        protected Criteria(AswxmallRebatesCreateOrderExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public AswxmallRebatesCreateOrderExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table aswxmall_rebates_create_order
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        void example(com.lzdn.aswxmall.db.domain.AswxmallRebatesCreateOrderExample example);
    }
}