package com.lzdn.aswxmall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class AswxmallRebatesCreateOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aswxmall_rebates_create_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aswxmall_rebates_create_order.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aswxmall_rebates_create_order.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aswxmall_rebates_create_order.order_user_id
     *
     * @mbg.generated
     */
    private Integer orderUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aswxmall_rebates_create_order.order_actual_price
     *
     * @mbg.generated
     */
    private BigDecimal orderActualPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aswxmall_rebates_create_order.before_amounts
     *
     * @mbg.generated
     */
    private BigDecimal beforeAmounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aswxmall_rebates_create_order.rebates
     *
     * @mbg.generated
     */
    private BigDecimal rebates;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aswxmall_rebates_create_order.balance
     *
     * @mbg.generated
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aswxmall_rebates_create_order.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aswxmall_rebates_create_order.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aswxmall_rebates_create_order.id
     *
     * @return the value of aswxmall_rebates_create_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aswxmall_rebates_create_order.id
     *
     * @param id the value for aswxmall_rebates_create_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aswxmall_rebates_create_order.user_id
     *
     * @return the value of aswxmall_rebates_create_order.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aswxmall_rebates_create_order.user_id
     *
     * @param userId the value for aswxmall_rebates_create_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aswxmall_rebates_create_order.order_id
     *
     * @return the value of aswxmall_rebates_create_order.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aswxmall_rebates_create_order.order_id
     *
     * @param orderId the value for aswxmall_rebates_create_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aswxmall_rebates_create_order.order_user_id
     *
     * @return the value of aswxmall_rebates_create_order.order_user_id
     *
     * @mbg.generated
     */
    public Integer getOrderUserId() {
        return orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aswxmall_rebates_create_order.order_user_id
     *
     * @param orderUserId the value for aswxmall_rebates_create_order.order_user_id
     *
     * @mbg.generated
     */
    public void setOrderUserId(Integer orderUserId) {
        this.orderUserId = orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aswxmall_rebates_create_order.order_actual_price
     *
     * @return the value of aswxmall_rebates_create_order.order_actual_price
     *
     * @mbg.generated
     */
    public BigDecimal getOrderActualPrice() {
        return orderActualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aswxmall_rebates_create_order.order_actual_price
     *
     * @param orderActualPrice the value for aswxmall_rebates_create_order.order_actual_price
     *
     * @mbg.generated
     */
    public void setOrderActualPrice(BigDecimal orderActualPrice) {
        this.orderActualPrice = orderActualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aswxmall_rebates_create_order.before_amounts
     *
     * @return the value of aswxmall_rebates_create_order.before_amounts
     *
     * @mbg.generated
     */
    public BigDecimal getBeforeAmounts() {
        return beforeAmounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aswxmall_rebates_create_order.before_amounts
     *
     * @param beforeAmounts the value for aswxmall_rebates_create_order.before_amounts
     *
     * @mbg.generated
     */
    public void setBeforeAmounts(BigDecimal beforeAmounts) {
        this.beforeAmounts = beforeAmounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aswxmall_rebates_create_order.rebates
     *
     * @return the value of aswxmall_rebates_create_order.rebates
     *
     * @mbg.generated
     */
    public BigDecimal getRebates() {
        return rebates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aswxmall_rebates_create_order.rebates
     *
     * @param rebates the value for aswxmall_rebates_create_order.rebates
     *
     * @mbg.generated
     */
    public void setRebates(BigDecimal rebates) {
        this.rebates = rebates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aswxmall_rebates_create_order.balance
     *
     * @return the value of aswxmall_rebates_create_order.balance
     *
     * @mbg.generated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aswxmall_rebates_create_order.balance
     *
     * @param balance the value for aswxmall_rebates_create_order.balance
     *
     * @mbg.generated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aswxmall_rebates_create_order.type
     *
     * @return the value of aswxmall_rebates_create_order.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aswxmall_rebates_create_order.type
     *
     * @param type the value for aswxmall_rebates_create_order.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aswxmall_rebates_create_order.create_time
     *
     * @return the value of aswxmall_rebates_create_order.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aswxmall_rebates_create_order.create_time
     *
     * @param createTime the value for aswxmall_rebates_create_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", orderId=").append(orderId);
        sb.append(", orderUserId=").append(orderUserId);
        sb.append(", orderActualPrice=").append(orderActualPrice);
        sb.append(", beforeAmounts=").append(beforeAmounts);
        sb.append(", rebates=").append(rebates);
        sb.append(", balance=").append(balance);
        sb.append(", type=").append(type);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AswxmallRebatesCreateOrder other = (AswxmallRebatesCreateOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getOrderUserId() == null ? other.getOrderUserId() == null : this.getOrderUserId().equals(other.getOrderUserId()))
            && (this.getOrderActualPrice() == null ? other.getOrderActualPrice() == null : this.getOrderActualPrice().equals(other.getOrderActualPrice()))
            && (this.getBeforeAmounts() == null ? other.getBeforeAmounts() == null : this.getBeforeAmounts().equals(other.getBeforeAmounts()))
            && (this.getRebates() == null ? other.getRebates() == null : this.getRebates().equals(other.getRebates()))
            && (this.getBalance() == null ? other.getBalance() == null : this.getBalance().equals(other.getBalance()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getOrderUserId() == null) ? 0 : getOrderUserId().hashCode());
        result = prime * result + ((getOrderActualPrice() == null) ? 0 : getOrderActualPrice().hashCode());
        result = prime * result + ((getBeforeAmounts() == null) ? 0 : getBeforeAmounts().hashCode());
        result = prime * result + ((getRebates() == null) ? 0 : getRebates().hashCode());
        result = prime * result + ((getBalance() == null) ? 0 : getBalance().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        userId("user_id", "userId", "INTEGER", false),
        orderId("order_id", "orderId", "INTEGER", false),
        orderUserId("order_user_id", "orderUserId", "INTEGER", false),
        orderActualPrice("order_actual_price", "orderActualPrice", "DECIMAL", false),
        beforeAmounts("before_amounts", "beforeAmounts", "DECIMAL", false),
        rebates("rebates", "rebates", "DECIMAL", false),
        balance("balance", "balance", "DECIMAL", false),
        type("type", "type", "TINYINT", true),
        createTime("create_time", "createTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table aswxmall_rebates_create_order
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}