package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallRebatesWithdrawalOrder;
import com.lzdn.aswxmall.db.domain.AswxmallRebatesWithdrawalOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallRebatesWithdrawalOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    long countByExample(AswxmallRebatesWithdrawalOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallRebatesWithdrawalOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    int insert(AswxmallRebatesWithdrawalOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallRebatesWithdrawalOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    AswxmallRebatesWithdrawalOrder selectOneByExample(AswxmallRebatesWithdrawalOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    AswxmallRebatesWithdrawalOrder selectOneByExampleSelective(@Param("example") AswxmallRebatesWithdrawalOrderExample example, @Param("selective") AswxmallRebatesWithdrawalOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    List<AswxmallRebatesWithdrawalOrder> selectByExampleSelective(@Param("example") AswxmallRebatesWithdrawalOrderExample example, @Param("selective") AswxmallRebatesWithdrawalOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    List<AswxmallRebatesWithdrawalOrder> selectByExample(AswxmallRebatesWithdrawalOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    AswxmallRebatesWithdrawalOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallRebatesWithdrawalOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    AswxmallRebatesWithdrawalOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallRebatesWithdrawalOrder record, @Param("example") AswxmallRebatesWithdrawalOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallRebatesWithdrawalOrder record, @Param("example") AswxmallRebatesWithdrawalOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallRebatesWithdrawalOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_withdrawal_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallRebatesWithdrawalOrder record);
}