package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallFeedback;
import com.lzdn.aswxmall.db.domain.AswxmallFeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    long countByExample(AswxmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    int insert(AswxmallFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    AswxmallFeedback selectOneByExample(AswxmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    AswxmallFeedback selectOneByExampleSelective(@Param("example") AswxmallFeedbackExample example, @Param("selective") AswxmallFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    List<AswxmallFeedback> selectByExampleSelective(@Param("example") AswxmallFeedbackExample example, @Param("selective") AswxmallFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    List<AswxmallFeedback> selectByExample(AswxmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    AswxmallFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    AswxmallFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    AswxmallFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallFeedback record, @Param("example") AswxmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallFeedback record, @Param("example") AswxmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}