package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallUser;
import com.lzdn.aswxmall.db.domain.AswxmallUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    long countByExample(AswxmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    int insert(AswxmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    AswxmallUser selectOneByExample(AswxmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    AswxmallUser selectOneByExampleSelective(@Param("example") AswxmallUserExample example, @Param("selective") AswxmallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    List<AswxmallUser> selectByExampleSelective(@Param("example") AswxmallUserExample example, @Param("selective") AswxmallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    List<AswxmallUser> selectByExample(AswxmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    AswxmallUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    AswxmallUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    AswxmallUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallUser record, @Param("example") AswxmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallUser record, @Param("example") AswxmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}