package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallCoupon;
import com.lzdn.aswxmall.db.domain.AswxmallCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    long countByExample(AswxmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    int insert(AswxmallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    AswxmallCoupon selectOneByExample(AswxmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    AswxmallCoupon selectOneByExampleSelective(@Param("example") AswxmallCouponExample example, @Param("selective") AswxmallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    List<AswxmallCoupon> selectByExampleSelective(@Param("example") AswxmallCouponExample example, @Param("selective") AswxmallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    List<AswxmallCoupon> selectByExample(AswxmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    AswxmallCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    AswxmallCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    AswxmallCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallCoupon record, @Param("example") AswxmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallCoupon record, @Param("example") AswxmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}