package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallCart;
import com.lzdn.aswxmall.db.domain.AswxmallCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    long countByExample(AswxmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    int insert(AswxmallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    AswxmallCart selectOneByExample(AswxmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    AswxmallCart selectOneByExampleSelective(@Param("example") AswxmallCartExample example, @Param("selective") AswxmallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    List<AswxmallCart> selectByExampleSelective(@Param("example") AswxmallCartExample example, @Param("selective") AswxmallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    List<AswxmallCart> selectByExample(AswxmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    AswxmallCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    AswxmallCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    AswxmallCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallCart record, @Param("example") AswxmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallCart record, @Param("example") AswxmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}