package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallAddress;
import com.lzdn.aswxmall.db.domain.AswxmallAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    long countByExample(AswxmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    int insert(AswxmallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    AswxmallAddress selectOneByExample(AswxmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    AswxmallAddress selectOneByExampleSelective(@Param("example") AswxmallAddressExample example, @Param("selective") AswxmallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    List<AswxmallAddress> selectByExampleSelective(@Param("example") AswxmallAddressExample example, @Param("selective") AswxmallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    List<AswxmallAddress> selectByExample(AswxmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    AswxmallAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    AswxmallAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    AswxmallAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallAddress record, @Param("example") AswxmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallAddress record, @Param("example") AswxmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_address
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}