package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallSystem;
import com.lzdn.aswxmall.db.domain.AswxmallSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    long countByExample(AswxmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    int insert(AswxmallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    AswxmallSystem selectOneByExample(AswxmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    AswxmallSystem selectOneByExampleSelective(@Param("example") AswxmallSystemExample example, @Param("selective") AswxmallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    List<AswxmallSystem> selectByExampleSelective(@Param("example") AswxmallSystemExample example, @Param("selective") AswxmallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    List<AswxmallSystem> selectByExample(AswxmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    AswxmallSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    AswxmallSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    AswxmallSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallSystem record, @Param("example") AswxmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallSystem record, @Param("example") AswxmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}