package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallUserReferrer;
import com.lzdn.aswxmall.db.domain.AswxmallUserReferrerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallUserReferrerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    long countByExample(AswxmallUserReferrerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallUserReferrerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    int insert(AswxmallUserReferrer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallUserReferrer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    AswxmallUserReferrer selectOneByExample(AswxmallUserReferrerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    AswxmallUserReferrer selectOneByExampleSelective(@Param("example") AswxmallUserReferrerExample example, @Param("selective") AswxmallUserReferrer.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    List<AswxmallUserReferrer> selectByExampleSelective(@Param("example") AswxmallUserReferrerExample example, @Param("selective") AswxmallUserReferrer.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    List<AswxmallUserReferrer> selectByExample(AswxmallUserReferrerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    AswxmallUserReferrer selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallUserReferrer.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    AswxmallUserReferrer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallUserReferrer record, @Param("example") AswxmallUserReferrerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallUserReferrer record, @Param("example") AswxmallUserReferrerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallUserReferrer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_referrer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallUserReferrer record);
}