package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallGrouponRules;
import com.lzdn.aswxmall.db.domain.AswxmallGrouponRulesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(AswxmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    int insert(AswxmallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    AswxmallGrouponRules selectOneByExample(AswxmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    AswxmallGrouponRules selectOneByExampleSelective(@Param("example") AswxmallGrouponRulesExample example, @Param("selective") AswxmallGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    List<AswxmallGrouponRules> selectByExampleSelective(@Param("example") AswxmallGrouponRulesExample example, @Param("selective") AswxmallGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    List<AswxmallGrouponRules> selectByExample(AswxmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    AswxmallGrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    AswxmallGrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    AswxmallGrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallGrouponRules record, @Param("example") AswxmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallGrouponRules record, @Param("example") AswxmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}