package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallComment;
import com.lzdn.aswxmall.db.domain.AswxmallCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    long countByExample(AswxmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    int insert(AswxmallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    AswxmallComment selectOneByExample(AswxmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    AswxmallComment selectOneByExampleSelective(@Param("example") AswxmallCommentExample example, @Param("selective") AswxmallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    List<AswxmallComment> selectByExampleSelective(@Param("example") AswxmallCommentExample example, @Param("selective") AswxmallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    List<AswxmallComment> selectByExample(AswxmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    AswxmallComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    AswxmallComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    AswxmallComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallComment record, @Param("example") AswxmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallComment record, @Param("example") AswxmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}