package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallAdmin;
import com.lzdn.aswxmall.db.domain.AswxmallAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    long countByExample(AswxmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    int insert(AswxmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    AswxmallAdmin selectOneByExample(AswxmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    AswxmallAdmin selectOneByExampleSelective(@Param("example") AswxmallAdminExample example, @Param("selective") AswxmallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    List<AswxmallAdmin> selectByExampleSelective(@Param("example") AswxmallAdminExample example, @Param("selective") AswxmallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    List<AswxmallAdmin> selectByExample(AswxmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    AswxmallAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    AswxmallAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    AswxmallAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallAdmin record, @Param("example") AswxmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallAdmin record, @Param("example") AswxmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}