package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallCouponUser;
import com.lzdn.aswxmall.db.domain.AswxmallCouponUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(AswxmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    int insert(AswxmallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    AswxmallCouponUser selectOneByExample(AswxmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    AswxmallCouponUser selectOneByExampleSelective(@Param("example") AswxmallCouponUserExample example, @Param("selective") AswxmallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    List<AswxmallCouponUser> selectByExampleSelective(@Param("example") AswxmallCouponUserExample example, @Param("selective") AswxmallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    List<AswxmallCouponUser> selectByExample(AswxmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    AswxmallCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    AswxmallCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    AswxmallCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallCouponUser record, @Param("example") AswxmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallCouponUser record, @Param("example") AswxmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}