package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallRebatesCreateOrder;
import com.lzdn.aswxmall.db.domain.AswxmallRebatesCreateOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallRebatesCreateOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    long countByExample(AswxmallRebatesCreateOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallRebatesCreateOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    int insert(AswxmallRebatesCreateOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallRebatesCreateOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    AswxmallRebatesCreateOrder selectOneByExample(AswxmallRebatesCreateOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    AswxmallRebatesCreateOrder selectOneByExampleSelective(@Param("example") AswxmallRebatesCreateOrderExample example, @Param("selective") AswxmallRebatesCreateOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    List<AswxmallRebatesCreateOrder> selectByExampleSelective(@Param("example") AswxmallRebatesCreateOrderExample example, @Param("selective") AswxmallRebatesCreateOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    List<AswxmallRebatesCreateOrder> selectByExample(AswxmallRebatesCreateOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    AswxmallRebatesCreateOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallRebatesCreateOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    AswxmallRebatesCreateOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallRebatesCreateOrder record, @Param("example") AswxmallRebatesCreateOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallRebatesCreateOrder record, @Param("example") AswxmallRebatesCreateOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallRebatesCreateOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_rebates_create_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallRebatesCreateOrder record);
}