package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallUserFormid;
import com.lzdn.aswxmall.db.domain.AswxmallUserFormidExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallUserFormidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    long countByExample(AswxmallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    int insert(AswxmallUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    AswxmallUserFormid selectOneByExample(AswxmallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    AswxmallUserFormid selectOneByExampleSelective(@Param("example") AswxmallUserFormidExample example, @Param("selective") AswxmallUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    List<AswxmallUserFormid> selectByExampleSelective(@Param("example") AswxmallUserFormidExample example, @Param("selective") AswxmallUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    List<AswxmallUserFormid> selectByExample(AswxmallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    AswxmallUserFormid selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    AswxmallUserFormid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    AswxmallUserFormid selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallUserFormid record, @Param("example") AswxmallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallUserFormid record, @Param("example") AswxmallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_user_formid
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}