package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallTopic;
import com.lzdn.aswxmall.db.domain.AswxmallTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    long countByExample(AswxmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    int insert(AswxmallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    AswxmallTopic selectOneByExample(AswxmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    AswxmallTopic selectOneByExampleSelective(@Param("example") AswxmallTopicExample example, @Param("selective") AswxmallTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    AswxmallTopic selectOneByExampleWithBLOBs(AswxmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    List<AswxmallTopic> selectByExampleSelective(@Param("example") AswxmallTopicExample example, @Param("selective") AswxmallTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    List<AswxmallTopic> selectByExampleWithBLOBs(AswxmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    List<AswxmallTopic> selectByExample(AswxmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    AswxmallTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    AswxmallTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    AswxmallTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallTopic record, @Param("example") AswxmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") AswxmallTopic record, @Param("example") AswxmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallTopic record, @Param("example") AswxmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(AswxmallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}