package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallGroupon;
import com.lzdn.aswxmall.db.domain.AswxmallGrouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    long countByExample(AswxmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    int insert(AswxmallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    AswxmallGroupon selectOneByExample(AswxmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    AswxmallGroupon selectOneByExampleSelective(@Param("example") AswxmallGrouponExample example, @Param("selective") AswxmallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    List<AswxmallGroupon> selectByExampleSelective(@Param("example") AswxmallGrouponExample example, @Param("selective") AswxmallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    List<AswxmallGroupon> selectByExample(AswxmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    AswxmallGroupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    AswxmallGroupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    AswxmallGroupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallGroupon record, @Param("example") AswxmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallGroupon record, @Param("example") AswxmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}