package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallFootprint;
import com.lzdn.aswxmall.db.domain.AswxmallFootprintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    long countByExample(AswxmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    int insert(AswxmallFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    AswxmallFootprint selectOneByExample(AswxmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    AswxmallFootprint selectOneByExampleSelective(@Param("example") AswxmallFootprintExample example, @Param("selective") AswxmallFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    List<AswxmallFootprint> selectByExampleSelective(@Param("example") AswxmallFootprintExample example, @Param("selective") AswxmallFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    List<AswxmallFootprint> selectByExample(AswxmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    AswxmallFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    AswxmallFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    AswxmallFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallFootprint record, @Param("example") AswxmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallFootprint record, @Param("example") AswxmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}