package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallStorage;
import com.lzdn.aswxmall.db.domain.AswxmallStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    long countByExample(AswxmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    int insert(AswxmallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    AswxmallStorage selectOneByExample(AswxmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    AswxmallStorage selectOneByExampleSelective(@Param("example") AswxmallStorageExample example, @Param("selective") AswxmallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    List<AswxmallStorage> selectByExampleSelective(@Param("example") AswxmallStorageExample example, @Param("selective") AswxmallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    List<AswxmallStorage> selectByExample(AswxmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    AswxmallStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    AswxmallStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    AswxmallStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallStorage record, @Param("example") AswxmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallStorage record, @Param("example") AswxmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}