package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallRegion;
import com.lzdn.aswxmall.db.domain.AswxmallRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    long countByExample(AswxmallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    int insert(AswxmallRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    AswxmallRegion selectOneByExample(AswxmallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    AswxmallRegion selectOneByExampleSelective(@Param("example") AswxmallRegionExample example, @Param("selective") AswxmallRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    List<AswxmallRegion> selectByExampleSelective(@Param("example") AswxmallRegionExample example, @Param("selective") AswxmallRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    List<AswxmallRegion> selectByExample(AswxmallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    AswxmallRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    AswxmallRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallRegion record, @Param("example") AswxmallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallRegion record, @Param("example") AswxmallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallRegion record);
}