package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallGoodsAttribute;
import com.lzdn.aswxmall.db.domain.AswxmallGoodsAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(AswxmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    int insert(AswxmallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    AswxmallGoodsAttribute selectOneByExample(AswxmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    AswxmallGoodsAttribute selectOneByExampleSelective(@Param("example") AswxmallGoodsAttributeExample example, @Param("selective") AswxmallGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    List<AswxmallGoodsAttribute> selectByExampleSelective(@Param("example") AswxmallGoodsAttributeExample example, @Param("selective") AswxmallGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    List<AswxmallGoodsAttribute> selectByExample(AswxmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    AswxmallGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    AswxmallGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    AswxmallGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallGoodsAttribute record, @Param("example") AswxmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallGoodsAttribute record, @Param("example") AswxmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}