package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallCollect;
import com.lzdn.aswxmall.db.domain.AswxmallCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    long countByExample(AswxmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    int insert(AswxmallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    AswxmallCollect selectOneByExample(AswxmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    AswxmallCollect selectOneByExampleSelective(@Param("example") AswxmallCollectExample example, @Param("selective") AswxmallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    List<AswxmallCollect> selectByExampleSelective(@Param("example") AswxmallCollectExample example, @Param("selective") AswxmallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    List<AswxmallCollect> selectByExample(AswxmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    AswxmallCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    AswxmallCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    AswxmallCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallCollect record, @Param("example") AswxmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallCollect record, @Param("example") AswxmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}