package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallOrder;
import com.lzdn.aswxmall.db.domain.AswxmallOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    long countByExample(AswxmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    int insert(AswxmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    AswxmallOrder selectOneByExample(AswxmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    AswxmallOrder selectOneByExampleSelective(@Param("example") AswxmallOrderExample example, @Param("selective") AswxmallOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    List<AswxmallOrder> selectByExampleSelective(@Param("example") AswxmallOrderExample example, @Param("selective") AswxmallOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    List<AswxmallOrder> selectByExample(AswxmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    AswxmallOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    AswxmallOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    AswxmallOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallOrder record, @Param("example") AswxmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallOrder record, @Param("example") AswxmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}