package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallGoodsProduct;
import com.lzdn.aswxmall.db.domain.AswxmallGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    long countByExample(AswxmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    int insert(AswxmallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    AswxmallGoodsProduct selectOneByExample(AswxmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    AswxmallGoodsProduct selectOneByExampleSelective(@Param("example") AswxmallGoodsProductExample example, @Param("selective") AswxmallGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    List<AswxmallGoodsProduct> selectByExampleSelective(@Param("example") AswxmallGoodsProductExample example, @Param("selective") AswxmallGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    List<AswxmallGoodsProduct> selectByExample(AswxmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    AswxmallGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    AswxmallGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    AswxmallGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallGoodsProduct record, @Param("example") AswxmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallGoodsProduct record, @Param("example") AswxmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}