package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallLog;
import com.lzdn.aswxmall.db.domain.AswxmallLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    long countByExample(AswxmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    int insert(AswxmallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    AswxmallLog selectOneByExample(AswxmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    AswxmallLog selectOneByExampleSelective(@Param("example") AswxmallLogExample example, @Param("selective") AswxmallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    List<AswxmallLog> selectByExampleSelective(@Param("example") AswxmallLogExample example, @Param("selective") AswxmallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    List<AswxmallLog> selectByExample(AswxmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    AswxmallLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    AswxmallLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    AswxmallLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallLog record, @Param("example") AswxmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallLog record, @Param("example") AswxmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}