package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallPermission;
import com.lzdn.aswxmall.db.domain.AswxmallPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    long countByExample(AswxmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    int insert(AswxmallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    AswxmallPermission selectOneByExample(AswxmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    AswxmallPermission selectOneByExampleSelective(@Param("example") AswxmallPermissionExample example, @Param("selective") AswxmallPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    List<AswxmallPermission> selectByExampleSelective(@Param("example") AswxmallPermissionExample example, @Param("selective") AswxmallPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    List<AswxmallPermission> selectByExample(AswxmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    AswxmallPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    AswxmallPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    AswxmallPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallPermission record, @Param("example") AswxmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallPermission record, @Param("example") AswxmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}