package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallGoodsSpecification;
import com.lzdn.aswxmall.db.domain.AswxmallGoodsSpecificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(AswxmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    int insert(AswxmallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    AswxmallGoodsSpecification selectOneByExample(AswxmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    AswxmallGoodsSpecification selectOneByExampleSelective(@Param("example") AswxmallGoodsSpecificationExample example, @Param("selective") AswxmallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    List<AswxmallGoodsSpecification> selectByExampleSelective(@Param("example") AswxmallGoodsSpecificationExample example, @Param("selective") AswxmallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    List<AswxmallGoodsSpecification> selectByExample(AswxmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    AswxmallGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    AswxmallGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    AswxmallGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallGoodsSpecification record, @Param("example") AswxmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallGoodsSpecification record, @Param("example") AswxmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}