package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallBrand;
import com.lzdn.aswxmall.db.domain.AswxmallBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    long countByExample(AswxmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    int insert(AswxmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    AswxmallBrand selectOneByExample(AswxmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    AswxmallBrand selectOneByExampleSelective(@Param("example") AswxmallBrandExample example, @Param("selective") AswxmallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    List<AswxmallBrand> selectByExampleSelective(@Param("example") AswxmallBrandExample example, @Param("selective") AswxmallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    List<AswxmallBrand> selectByExample(AswxmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    AswxmallBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    AswxmallBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    AswxmallBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallBrand record, @Param("example") AswxmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallBrand record, @Param("example") AswxmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}