package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallKeyword;
import com.lzdn.aswxmall.db.domain.AswxmallKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    long countByExample(AswxmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    int insert(AswxmallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    AswxmallKeyword selectOneByExample(AswxmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    AswxmallKeyword selectOneByExampleSelective(@Param("example") AswxmallKeywordExample example, @Param("selective") AswxmallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    List<AswxmallKeyword> selectByExampleSelective(@Param("example") AswxmallKeywordExample example, @Param("selective") AswxmallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    List<AswxmallKeyword> selectByExample(AswxmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    AswxmallKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    AswxmallKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    AswxmallKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallKeyword record, @Param("example") AswxmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallKeyword record, @Param("example") AswxmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}