package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallOrderGoods;
import com.lzdn.aswxmall.db.domain.AswxmallOrderGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    long countByExample(AswxmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    int insert(AswxmallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    AswxmallOrderGoods selectOneByExample(AswxmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    AswxmallOrderGoods selectOneByExampleSelective(@Param("example") AswxmallOrderGoodsExample example, @Param("selective") AswxmallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    List<AswxmallOrderGoods> selectByExampleSelective(@Param("example") AswxmallOrderGoodsExample example, @Param("selective") AswxmallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    List<AswxmallOrderGoods> selectByExample(AswxmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    AswxmallOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    AswxmallOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    AswxmallOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallOrderGoods record, @Param("example") AswxmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallOrderGoods record, @Param("example") AswxmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}