package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallGoods;
import com.lzdn.aswxmall.db.domain.AswxmallGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    long countByExample(AswxmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    int insert(AswxmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    AswxmallGoods selectOneByExample(AswxmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    AswxmallGoods selectOneByExampleSelective(@Param("example") AswxmallGoodsExample example, @Param("selective") AswxmallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    AswxmallGoods selectOneByExampleWithBLOBs(AswxmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    List<AswxmallGoods> selectByExampleSelective(@Param("example") AswxmallGoodsExample example, @Param("selective") AswxmallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    List<AswxmallGoods> selectByExampleWithBLOBs(AswxmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    List<AswxmallGoods> selectByExample(AswxmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    AswxmallGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    AswxmallGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    AswxmallGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallGoods record, @Param("example") AswxmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") AswxmallGoods record, @Param("example") AswxmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallGoods record, @Param("example") AswxmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(AswxmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}