package com.lzdn.aswxmall.db.dao;

import com.lzdn.aswxmall.db.domain.AswxmallIssue;
import com.lzdn.aswxmall.db.domain.AswxmallIssueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AswxmallIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    long countByExample(AswxmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    int deleteByExample(AswxmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    int insert(AswxmallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    int insertSelective(AswxmallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    AswxmallIssue selectOneByExample(AswxmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    AswxmallIssue selectOneByExampleSelective(@Param("example") AswxmallIssueExample example, @Param("selective") AswxmallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    List<AswxmallIssue> selectByExampleSelective(@Param("example") AswxmallIssueExample example, @Param("selective") AswxmallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    List<AswxmallIssue> selectByExample(AswxmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    AswxmallIssue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AswxmallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    AswxmallIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    AswxmallIssue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AswxmallIssue record, @Param("example") AswxmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AswxmallIssue record, @Param("example") AswxmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AswxmallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AswxmallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AswxmallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aswxmall_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}